In [13]:
import torch
import numpy as np
a = torch.tensor([6, 7])
b = torch.tensor(((2, 4), (5, 8)))
c = torch.tensor(np.ones((2, 3)))
print(f'Tensor a:', a)
print(f'Tensor b', b)
print(f'Tensor c', c)

Tensor a: tensor([6, 7])
Tensor b tensor([[2, 4],
        [5, 8]])
Tensor c tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [19]:
x = torch.ones((2, 3))
y = torch.zeros(2, 3)
z = torch.empty((2, 3))
print(f'Tensor x', x)
print(f'Tensor y', y)
print(f'Tensor z', z)

Tensor x tensor([[1., 1., 1.],
        [1., 1., 1.]])
Tensor y tensor([[0., 0., 0.],
        [0., 0., 0.]])
Tensor z tensor([[6.2450e-39, 1.0653e-38, 8.4490e-39],
        [1.0194e-38, 8.9082e-39, 8.4490e-39]])


In [28]:
a = torch.rand(1, 3)
b = torch.randn(3, 4)
c = torch.rand_like(a)
d = torch.randn_like(b)
e = torch.empty_like(a)
print(f'Tensor a', a)
print(f'Tensor b', b)
print(f'Tensor c', c)
print(f'Tensor d', d)
print(f'Tensor e', e)

Tensor a tensor([[0.9375, 0.9106, 0.1144]])
Tensor b tensor([[ 0.7794, -0.9062,  0.3897,  0.6481],
        [ 1.0483,  0.9488,  0.3928,  1.3814],
        [ 0.6748, -1.0393, -0.5039, -1.0821]])
Tensor c tensor([[0.1484, 0.3823, 0.2099]])
Tensor d tensor([[-0.0285,  0.1036,  1.2678, -0.7225],
        [ 0.4156, -0.5506,  0.7180,  0.9685],
        [ 0.8777,  0.0036,  0.9915, -0.9978]])
Tensor e tensor([[9.1477e-41, 0.0000e+00, 5.6052e-45]])


In [29]:
import random
def set_seed(seed=None, seed_torch=True):
    """
    Function that controls randomness. NumPy and random modules must be imported.

    Args:
        seed : Integer
        A non-negative integer that defines the random state. Default is `None`.
        seed_torch : Boolean
        If `True` sets the random seed for pytorch tensors, so pytorch module
        must be imported. Default is `True`.

    Returns:
        Nothing.
    """
    if seed is None:
        seed = np.random.choice(2 ** 32)
    random.seed(seed)
    np.random.seed(seed)
    if seed_torch:
        torch.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
        torch.cuda.manual_seed(seed)
        torch.backends.cudnn.benchmark = False
        torch.backends.cudnn.deterministic = True

    print(f'Random seed {seed} has been set.')

In [33]:
def simplefun(seed=True, my_seed=None):
  """
  Helper function to verify effectiveness of set_seed attribute

  Args:
    seed: Boolean
      Specifies if seed value is provided or not
    my_seed: Integer
      Initializes seed to specified value

  Returns:
    Nothing
  """
  if seed:
    set_seed(seed=my_seed)

  # uniform distribution
  a = torch.rand(1, 3)
  # normal distribution
  b = torch.randn(3, 4)

  print("Tensor a: ", a)
  print("Tensor b: ", b)

In [34]:
simplefun(seed=True, my_seed=0)  # Turn `seed` to `False` or change `my_seed`


Random seed 0 has been set.
Tensor a:  tensor([[0.4963, 0.7682, 0.0885]])
Tensor b:  tensor([[ 0.3643,  0.1344,  0.1642,  0.3058],
        [ 0.2100,  0.9056,  0.6035,  0.8110],
        [-0.0451,  0.8797,  1.0482, -0.0445]])


In [43]:
x = np.arange(1, 22, 2)
print(f'Numpy x: {x}')

Numpy x: [ 1  3  5  7  9 11 13 15 17 19 21]


In [44]:
x = torch.arange(1, 22, 2)
print(f'Torch x: {x}')

Torch x: tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])


In [45]:
y = np.linspace(1, 5, 10)
print(f'Numpy y: {y}')

Numpy y: [1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [47]:
y = torch.linspace(1, 5, 10)
print(f'Torch y: {y}')

Torch y: tensor([1.0000, 1.4444, 1.8889, 2.3333, 2.7778, 3.2222, 3.6667, 4.1111, 4.5556,
        5.0000])


In [60]:
def tensor_creation(Z):
    """
    A function that creates various tensors.

    Args:
        Z: numpy.ndarray
        An array of shape (3,4)

    Returns:
        A : Tensor
        2 by 3 tensor consisting of ones
        B : Tensor
        A tensor with elements equal to the elements of numpy array Z
        C : Tensor
        A tensor with the same number of elements as A but with values ∼U(0,1)
        D : Tensor
        A 1D tensor containing the even numbers between 4 and 40 inclusive.
    """


    # raise NotImplementedError("Student exercise: say what they should have done")

    A = torch.ones((2, 3))
    B = torch.tensor(Z)
    C = torch.zeros_like(a)
    D = torch.arange(2, 41, 2)

    return A, B, C, D


# numpy array to copy later
Z = np.vander([1, 2, 3], 4)

# Uncomment below to check your function!
A, B, C, D = tensor_creation(Z)
print(A)
print(B)
print(C)
print(D)


tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 1,  1,  1,  1],
        [ 8,  4,  2,  1],
        [27,  9,  3,  1]], dtype=torch.int32)
tensor([[0., 0., 0.]])
tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
        38, 40])


In [66]:
x = torch.tensor(np.array([2, 3, 4]))
y = torch.ones(1, 3)
torch.multiply(x, y, out=a)
print(f'Tensor a: {a}')

Tensor a: tensor([[2., 3., 4.]])


In [67]:
a = torch.ones(5, 3)
b = torch.rand(5, 3)
c = torch.empty(5, 3)
d = torch.empty(5, 3)

# this only works if c and d already exist
torch.add(a, b, out=c)

# Pointwise Multiplication of a and b
torch.multiply(a, b, out=d)

print(c)
print(d)

tensor([[1.0362, 1.1852, 1.3734],
        [1.3051, 1.9320, 1.1759],
        [1.2698, 1.1507, 1.0317],
        [1.2081, 1.9298, 1.7231],
        [1.7423, 1.5263, 1.2437]])
tensor([[0.0362, 0.1852, 0.3734],
        [0.3051, 0.9320, 0.1759],
        [0.2698, 0.1507, 0.0317],
        [0.2081, 0.9298, 0.7231],
        [0.7423, 0.5263, 0.2437]])


In [68]:
a + b

tensor([[1.0362, 1.1852, 1.3734],
        [1.3051, 1.9320, 1.1759],
        [1.2698, 1.1507, 1.0317],
        [1.2081, 1.9298, 1.7231],
        [1.7423, 1.5263, 1.2437]])

In [70]:
x = torch.rand(3, 3)
print(x)
print("\n")
# sum() - note the axis is the axis you move across when summing
print(f"Sum of every element of x: {x.sum()}")
print(f"Sum of the columns of x: {x.sum(axis=0)}")
print(f"Sum of the rows of x: {x.sum(axis=1)}")
print("\n")

print(f"Mean value of all elements of x {x.mean()}")
print(f"Mean values of the columns of x {x.mean(axis=0)}")
print(f"Mean values of the rows of x {x.mean(axis=1)}")


tensor([[0.9971, 0.6984, 0.5675],
        [0.8352, 0.2056, 0.5932],
        [0.1123, 0.1535, 0.2417]])


Sum of every element of x: 4.404580116271973
Sum of the columns of x: tensor([1.9447, 1.0575, 1.4024])
Sum of the rows of x: tensor([2.2631, 1.6340, 0.5075])


Mean value of all elements of x 0.489397794008255
Mean values of the columns of x tensor([0.6482, 0.3525, 0.4675])
Mean values of the rows of x tensor([0.7544, 0.5447, 0.1692])


In [79]:
def simple_operations(a1: torch.Tensor, a2: torch.Tensor, a3: torch.Tensor):
    """
    Helper function to demonstrate simple operations
    i.e., Multiplication of tensor a1 with tensor a2 and then add it with tensor a3

    Args:
        a1: Torch tensor
        Tensor of size ([2,2])
        a2: Torch tensor
        Tensor of size ([2,2])
        a3: Torch tensor
        Tensor of size ([2,2])

    Returns:
        answer: Torch tensor
        Tensor of size ([2,2]) resulting from a1 multiplied with a2, added with a3
    """


    answer = a1 @ a2 + a3
    return answer


# Computing expression 1:

# init our tensors
a1 = torch.tensor([[2, 4], [5, 7]])
a2 = torch.tensor([[1, 1], [2, 3]])
a3 = torch.tensor([[10, 10], [12, 1]])
## uncomment to test your function
A = simple_operations(a1, a2, a3)
print(A)

tensor([[20, 24],
        [31, 27]])


In [87]:
def dot_product(b1: torch.Tensor, b2: torch.Tensor):

    """
    Helper function to demonstrate dot product operation
    Dot product is an algebraic operation that takes two equal-length sequences
    (usually coordinate vectors), and returns a single number.
    Geometrically, it is the product of the Euclidean magnitudes of the
    two vectors and the cosine of the angle between them.

    Args:
        b1: Torch tensor
        Tensor of size ([3])
        b2: Torch tensor
        Tensor of size ([3])

    Returns:
        product: Tensor
        Tensor of size ([1]) resulting from b1 scalar multiplied with b2
    """
    # Use torch.dot() to compute the dot product of two tensors
    product = b1.dot(b2)

    return product


# Computing expression 2:
b1 = torch.tensor([3, 5, 7])
b2 = torch.tensor([2, 4, 8])
## Uncomment to test your function
b = dot_product(b1, b2)
print(b)

tensor(82)


In [95]:
x = torch.rand(1, 2, 3, 4, 5)
print(f'x[0] shape: {x[0].shape}')
print(f'x[0][0]: {x[0][0].shape}')

x[0] shape: torch.Size([2, 3, 4, 5])
x[0][0]: torch.Size([3, 4, 5])


In [97]:
x = torch.arange(0, 12).reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [99]:
z = x.flatten()
z

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [107]:
x = torch.randn(1, 10)

print(x)
print(x[0])

tensor([[ 1.5200,  2.1485, -0.7698, -1.2158, -0.9272,  1.1721,  1.1462,  1.2611,
          0.2332,  0.1456]])
tensor([ 1.5200,  2.1485, -0.7698, -1.2158, -0.9272,  1.1721,  1.1462,  1.2611,
         0.2332,  0.1456])


In [110]:
x = x.squeeze()
x

tensor([ 1.5200,  2.1485, -0.7698, -1.2158, -0.9272,  1.1721,  1.1462,  1.2611,
         0.2332,  0.1456])

In [113]:
y = x.unsqueeze(0)
y

tensor([[ 1.5200,  2.1485, -0.7698, -1.2158, -0.9272,  1.1721,  1.1462,  1.2611,
          0.2332,  0.1456]])

In [117]:
# Adding singleton dimensions works a similar way, and is often used when tensors
# being added need same number of dimensions

y = torch.randn(5, 5)
print(f"Shape of y: {y.shape}")
print(y)
# lets insert a singleton dimension
y = y.unsqueeze(1)
print(f"Shape of y: {y.shape}")
y

Shape of y: torch.Size([5, 5])
tensor([[-1.7934, -1.8932,  1.0428, -0.4526,  0.2269],
        [ 0.3287,  0.7297,  1.9877,  1.2183, -0.1547],
        [-0.2846, -0.6296, -0.2486,  0.8057, -1.1019],
        [-0.7408,  0.8241, -0.9503,  0.6593, -0.6863],
        [-0.2917,  1.8699, -1.1054, -0.1442, -0.3463]])
Shape of y: torch.Size([5, 1, 5])


tensor([[[-1.7934, -1.8932,  1.0428, -0.4526,  0.2269]],

        [[ 0.3287,  0.7297,  1.9877,  1.2183, -0.1547]],

        [[-0.2846, -0.6296, -0.2486,  0.8057, -1.1019]],

        [[-0.7408,  0.8241, -0.9503,  0.6593, -0.6863]],

        [[-0.2917,  1.8699, -1.1054, -0.1442, -0.3463]]])

In [118]:
x = torch.randn(5)
print(f"x: {x}  |  x type:  {x.type()}")

y = x.numpy()
print(f"y: {y}  |  y type:  {type(y)}")

z = torch.tensor(y)
print(f"z: {z}  |  z type:  {z.type()}")

x: tensor([-1.0284, -0.3537, -0.1650,  0.6599, -1.3217])  |  x type:  torch.FloatTensor
y: [-1.0283703  -0.35368153 -0.16499282  0.6598884  -1.3216829 ]  |  y type:  <class 'numpy.ndarray'>
z: tensor([-1.0284, -0.3537, -0.1650,  0.6599, -1.3217])  |  z type:  torch.FloatTensor


In [120]:
x = torch.arange(0, 12).reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [130]:
# y = x.unsqueeze(0)
# y

In [134]:
perm = x.permute(1, 0)
perm

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [139]:
z= torch.concat((x, x))
z

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [145]:
t = torch.concat((x, x), axis=1)
t

tensor([[ 0,  1,  2,  3,  0,  1,  2,  3],
        [ 4,  5,  6,  7,  4,  5,  6,  7],
        [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [148]:
w = x.transpose(1,0)
w

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [152]:
def A(a1, a2):
    x = a2.sum()
    y = a1.sum(axis=1)
    return x * y
a1 = torch.ones(2, 2)
a2 = torch.tensor([[1, 2, 3], [1, 2, 3]])
A(a1, a2)

tensor([24., 24.])

In [154]:
a = a2.flatten()
a

tensor([1, 2, 3, 1, 2, 3])

In [171]:
def B(a1):
    flatted = a1.flatten()
    indices = np.arange(flatted.size)
    result = np.stack((flatted, indices), axis=1)
    return result
B(a1.numpy())

array([[1., 0.],
       [1., 1.],
       [1., 2.],
       [1., 3.]])

In [173]:
torch.cuda.is_available()

False

In [177]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
x = torch.tensor([3, 4], device=device)
x.device


device(type='cpu')

In [ ]:
from torchvision import datasets
datasets.CIFAR10(root='data', download=True)